CREATE TABLE trades (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL,
    qty TEXT,
    buy_price DECIMAL,
    sell_price DECIMAL,
    pnl DECIMAL,
    bought_time TEXT,
    sold_time TEXT,
    duration TEXT,
    bias TEXT,
    commodity TEXT,
    symbol TEXT,
    stop_price DECIMAL,
    target_price DECIMAL,
    entry_class TEXT,
    execution_model TEXT,
    variables_used TEXT,
    trade_feeling TEXT,
    trade_management TEXT,
    win_loss_percent TEXT,
    return_amount DECIMAL,
    risk_amount DECIMAL,
    risk_reward TEXT,
    trade_timestamp TEXT,
    status TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);